# used by make and deploy
language: python
python:
    - "3.7"

sudo: required
services:
    - docker
before_install:
    - docker build -t nizaevka/pycnfg -f Dockerfile.dev .

# command to install dependencies (default pip install -r requirements.txt)
# true = do nothing
install: true

# command to run tests
script:
    - docker run -e CI=true nizaevka/pycnfg pytest tests
#    - make test

# currently deploy on branch {vX.X or vX.X.X}
deploy:
    # pypi
    provider: pypi
    on:
        # Single branch
        # branch: master
        # For multiple branches:
        # $TRAVIS_BRANCH =~ ^(staging|production)$
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^v[0-9].*$
        # only on tagged direct (no PR) commit "git push origin --tags"
        # If the `tags` key is specified, the `branch` ignored.
        # tags: true
    user: "$PYPI_USERNAME"
    password:
      secure: "$PYPI_PASSWORD"
    distributions: "sdist bdist_wheel"
    # Skip already exist error.
    skip_existing: true
#     # test PyPi
#     provider: script
#     script: make deploy
#     on:
#        branch: feature

# Only if deploy on pypi. Use $TRAVIS_BRANCH as version.
after_deploy:
    - docker build -t nizaevka/pycnfg:$TRAVIS_BRANCH -f Dockerfile .
    # log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push to dockerhub
    - docker push nizaevka/pycnfg:$TRAVIS_BRANCH

# global whitelist.
# start travis build (exec yml) only on change to specific branch/tag.
# currently: master or {v1.3 / v1.4.5}
branches:
  only:
    - master
    - /^v[0-9].*$/
# more specific, not work in $TRAVIS_BRANCH
#    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/